### ISSUE TITLE
BTFS hostui - Copy button is not working

### ISSUE THREAD

**Issue by azorpax** [TRON-US/go-btfs#1200] opened 2021-11-26 10:42 UTC
Hi, the version i am using is 1.5.3 in docker or the ghcr.io/tron-us/go-btfs:release.
  
in the wallet page, the copy button is not working 
![image](https://user-images.githubusercontent.com/12295737/143567398-900085a8-b07a-485c-a7c1-c3eb4193973a.png)

browser console log:
![image](https://user-images.githubusercontent.com/12295737/143567663-f0db7523-674b-4b73-a9fe-7dcd5d2a8e2a.png)
![image](https://user-images.githubusercontent.com/12295737/143568328-369e0679-7eae-4d10-8f85-1f5e90539f5b.png)

**Comment by Sophia-yu-kk** [comment] 2021-11-29 06:59
![image](https://user-images.githubusercontent.com/56811501/143822202-25ecc650-e36d-49c4-843f-d18c0eefc961.png)

**Comment by Sophia-yu-kk** [comment] 2021-11-29 07:02
We have not reproduced the problem of your feedback, after testing is normal copy， thank you for your feedback.

**Comment by Sophia-yu-kk** [comment] 2021-11-29 07:15
Your feedback may be caused by cross-domain problems, you can refer to the document link,
https://docs.btfs.io/docs/btfs-dapp-guide#setup

**Comment by Sophia-yu-kk** [comment] 2021-11-29 07:28
Hello, thank you for your feedback, after the relevant department colleagues confirmed that this is a cross-domain problem, the problem has been recorded, and in the next version we will optimize this issue. Thank you very much for your feedback. Temporarily close this issue, if you have new questions, you can continue to feedback with us. Have a nice life.

**Closed by Sophia-yu-kk** 2021-11-29 07:28 UTC
