### ISSUE TITLE
Failed to sync host stats: Failed to query stats from Hub service: HubQueryClien t: Cannot query to get stats!

### ISSUE THREAD

**Issue by xinli6991** [TRON-US/go-btfs#705] opened 2020-09-18 05:58 UTC
Initializing daemon...
go-btfs version: 1.3.6-b1722d1
Repo version: 9
System version: amd64/windows
Golang version: go1.14.6
Repo location: J:\btfs_date
Node ID: 16Uiu2HAm2H6ntDp3ZLmGW6dJe7JtLVN1DmPMtWAsNZDGMUeruHXs
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.31.254/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/110.52.4.202/tcp/24984
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.31.254/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
HostUI: http://127.0.0.1:5001/hostui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Remote API server listening on /ip4/127.0.0.1/tcp/5101
Daemon is ready
Storage host info will be synced at [SCORE] mode
Current host stats will be synced
Current host settings will be synced
2020-09-18T13:46:36.140+0800    [31mERROR[0m  spin    spin/hosts.go:63
Failed to sync host stats: Failed to query stats from Hub service: HubQueryClien
t: Cannot query to get stats!
BTFS is up-to-date.

**Comment by xinli6991** [comment] 2020-09-18 06:03
16Uiu2HAm2H6ntDp3ZLmGW6dJe7JtLVN1DmPMtWAsNZDGMUeruHXs

**Comment by taiyangc** [comment] 2020-09-18 08:13
Duplicate of #702 Please track latest update there.

**Closed by taiyangc** 2020-09-18 08:13 UTC
