### ISSUE TITLE
INDEFINITE VALIDATION LOOP 

### ISSUE THREAD

**Issue by pavansantani** [TRON-US/go-btfs#648] opened 2020-08-18 10:21 UTC
MY NODE INTO VALIDATION

NODE ID: 16Uiu2HAkzRqkkqU6EMR24DLiU79WDnEvxLNNWMsg1hNEUbYdf1E3

journalctl -fu btfs
-- Logs begin at Sun 2020-08-02 08:29:39 UTC. --
Aug 16 06:46:06 btfs btfs[3741]: 2020-08-16T06:46:06.290Z ERROR upload upload/init.go:303 rpc error: code = Unknown desc = question not ready for renterPid 16Uiu2HAm1sJ9uwbEhbbTNy9Ep9aVgCUS2vqHTKFQJTQkAPrC1dBa fileHash QmcDiPA5KusNuNbTT88PzgmXBCoBwUJ9Y4uS4JBqqdqB4b shardHash QmXP3Qqhh5WmLue48tcBiCDnYrS8swRFtrozwygsqgQPpx contractId bb5bcd30-cf73-466c-938b-b8cc7f2be108,a3b1751a-719c-409d-a5b9-2606424a3117 , process will be continue in p2pCall
Aug 16 12:13:09 btfs btfs[3741]: BTFS is up-to-date.
Aug 17 12:13:14 btfs btfs[3741]: BTFS is up-to-date.
Aug 18 01:11:54 btfs btfs[3741]: 2020-08-18T01:11:54.533Z ERROR spin spin/hosts.go:63 Failed to sync HOST contracts: payout status batch returned wrong length of contracts, need 102, got 100
Aug 18 02:11:54 btfs btfs[3741]: 2020-08-18T02:11:54.514Z ERROR spin spin/hosts.go:63 Failed to sync HOST contracts: payout status batch returned wrong length of contracts, need 102, got 100
Aug 18 03:11:54 btfs btfs[3741]: 2020-08-18T03:11:54.551Z ERROR spin spin/hosts.go:63 Failed to sync HOST contracts: payout status batch returned wrong length of contracts, need 103, got 100
Aug 18 04:11:54 btfs btfs[3741]: 2020-08-18T04:11:54.518Z ERROR spin spin/hosts.go:63 Failed to sync HOST contracts: payout status batch returned wrong length of contracts, need 103, got 100
Aug 18 05:11:54 btfs btfs[3741]: 2020-08-18T05:11:54.817Z ERROR spin spin/hosts.go:63 Failed to sync HOST contracts: payout status batch returned wrong length of contracts, need 103, got 100
Aug 18 06:13:22 btfs btfs[3741]: 2020-08-18T06:13:22.596Z ERROR spin spin/hosts.go:63 Failed to sync HOST contracts: payout status batch returned wrong length of contracts, need 105, got 100
Aug 18 07:11:54 btfs btfs[3741]: 2020-08-18T07:11:54.531Z ERROR spin spin/hosts.go:63 Failed to sync HOST contracts: payout status batch returned wrong length of contracts, need 105, got 100

**Comment by kryptoviar** [comment] 2020-08-18 10:53
Same error here, node validating, score went down from 9 to 8.4

Initializing daemon...
go-btfs version: 1.3.5-20c165c
Repo version: 9
System version: amd64/windows
Golang version: go1.14.6
Repo location: d:\btfs
Node ID: 16Uiu2HAmJzbXMM2gEREHo2j8X2vuHuV92gKJVo4MVhfQ9qmHQSge
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.0.2/tcp/4001
Swarm listening on /ip6/2001:0:2851:782c:2c37:1487:af14:8c12/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.0.2/tcp/4001
Swarm announcing /ip4/80.235.115.237/tcp/4001
Swarm announcing /ip6/2001:0:2851:782c:2c37:1487:af14:8c12/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
HostUI: http://127.0.0.1:5001/hostui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Remote API server listening on /ip4/127.0.0.1/tcp/5101
Daemon is ready
Storage host info will be synced at [SCORE] mode
Current host stats will be synced
Current host settings will be synced
BTFS is up-to-date.
2020-08-17T18:42:57.128+0300    [31mERROR[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: context deadline exceeded
2020-08-17T19:28:04.589+0300    [31mERROR[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: context deadline exceeded
2020-08-17T19:32:18.994+0300    [31mERROR[0m  upload  upload/init.go:303      failed to download shard QmTnwAnfHCbXFu8PdQZ9wx9e3WLHiUZFFM92kG4d8LieWx from file QmaEwZHyGaJ81GcK13my898MXVKiMEnfQfhSkwYcTX5Rkk with contract id 913f2ea6-0726-4a43-99eb-60cbc6c150cf,763cb7eb-903a-4aaf-a67a-5b6dc58d8557: [failed to get block for QmYYhruLcnbKbVh2nD5CkrGXJgTNmg1hqPvwh82XAZu4Rz: context deadline exceeded]
2020-08-17T19:42:06.902+0300    [31mERROR[0m  upload  upload/init.go:303      failed to download shard QmRumqAeLVPQMvf2skZiR6yjWnFYQG9v29k8TeCJamPkEQ from file Qmc2WzsfNA2g1gkPGgVb46kZVQ9bKVogYZSXDqxpaJsx6L with contract id 5ae27b70-2331-4179-b406-d13317c62d8a,3de4a81d-0bbc-42a9-8522-aec693c9c9f6: [failed to get block for QmRR7zpWHu7ZDApZ2GEt1uWdGmHXU85WskXkjKKZSTrgGp: context deadline exceeded]
2020-08-17T22:23:41.502+0300    [31mERROR[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: context deadline exceeded
2020-08-17T22:43:24.290+0300    [31mERROR[0m  upload  upload/init.go:303      failed to download shard QmQqT9ioNE5yTv85chiF8m721fqLwGfEbzhjVAC8pbpaWA from file QmeSjqLk8nwejzyJpZ7WxEb4wKjXNLt9Yz1ynp5vk3PXaS with contract id 8fc41735-b020-4162-9aa1-b194b869c266,d2834ecc-2c07-47f0-a20e-4c199a06b08f: [failed to get block for QmSe2RHiN2ej1NtRR5pqNsEJGvVN8wwEwAiqFjCPx7u1Fe: context deadline exceeded]
2020-08-17T23:49:20.534+0300    [31mERROR[0m  storage/contracts       upload/contracts.go:432 get payout status batch error:rpc error: code = Canceled desc = context canceled
2020-08-18T01:02:35.827+0300    [31mERROR[0m  spin    spin/analytics.go:209   failed to send data to status server: context deadline exceeded
2020-08-18T01:03:06.435+0300    [31mERROR[0m  spin    spin/analytics.go:209   failed to send data to status server: context deadline exceeded
2020-08-18T03:47:09.249+0300    [31mERROR[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: payout status batch returned wrong length of contracts, need 1129, got 100
2020-08-18T04:47:09.133+0300    [31mERROR[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: payout status batch returned wrong length of contracts, need 1129, got 100
2020-08-18T06:05:31.063+0300    [31mERROR[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: context deadline exceeded
2020-08-18T06:09:01.818+0300    [31mERROR[0m  upload  upload/init.go:303      failed to download shard QmeyKTuLkgGjRTz6byZo9JjHQ49tSyAZ8dSrUuBuN4HJpD from file QmZzAM5PWp2gmTxnKDiRyvh32GGMQJrp16CR2ziBv8dYa4 with contract id 9eb16e5e-fb3f-4fd2-bace-21c9528f086b,32895e0a-0636-4163-9124-d70f644d80ce: [failed to get block for QmeyKTuLkgGjRTz6byZo9JjHQ49tSyAZ8dSrUuBuN4HJpD: context deadline exceeded]
2020-08-18T06:47:09.352+0300    [31mERROR[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: payout status batch returned wrong length of contracts, need 1132, got 100
2020-08-18T07:47:09.040+0300    [31mERROR[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: payout status batch returned wrong length of contracts, need 1134, got 100
2020-08-18T08:47:10.013+0300    [31mERROR[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: payout status batch returned wrong length of contracts, need 1135, got 100
2020-08-18T09:47:09.160+0300    [31mERROR[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: payout status batch returned wrong length of contracts, need 1135, got 100
2020-08-18T10:47:09.227+0300    [31mERROR[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: payout status batch returned wrong length of contracts, need 1137, got 100
2020-08-18T11:47:09.852+0300    [31mERROR[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: payout status batch returned wrong length of contracts, need 1139, got 100
2020-08-18T12:47:08.946+0300    [31mERROR[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: payout status batch returned wrong length of contracts, need 1139, got 100
2020-08-18T13:47:09.181+0300    [31mERROR[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: payout status batch returned wrong length of contracts, need 1139, got 100

**Comment by WhiteHeadbanger** [comment] 2020-08-18 12:22
Same here

2020-08-17T21:59:10.735-0300    [31mERROR[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: payout status batch returned wrong length of contracts, need 1013, got 100
2020-08-17T22:59:04.516-0300    [31mERROR[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: payout status batch returned wrong length of contracts, need 1013, got 100
2020-08-17T23:59:04.308-0300    [31mERROR[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: payout status batch returned wrong length of contracts, need 1013, got 100
2020-08-18T00:59:04.254-0300    [31mERROR[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: payout status batch returned wrong length of contracts, need 1013, got 100
2020-08-18T01:59:04.379-0300    [31mERROR[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: payout status batch returned wrong length of contracts, need 1013, got 100
2020-08-18T02:59:04.435-0300    [31mERROR[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: payout status batch returned wrong length of contracts, need 1013, got 100
2020-08-18T03:59:22.157-0300    [31mERROR[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: payout status batch returned wrong length of contracts, need 1013, got 100
2020-08-18T04:59:27.966-0300    [31mERROR[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: payout status batch returned wrong length of contracts, need 1013, got 100
2020-08-18T05:59:30.700-0300    [31mERROR[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: payout status batch returned wrong length of contracts, need 1013, got 100
2020-08-18T06:59:28.887-0300    [31mERROR[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: payout status batch returned wrong length of contracts, need 1013, got 100
2020-08-18T07:59:30.912-0300    [31mERROR[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: payout status batch returned wrong length of contracts, need 1013, got 100
2020-08-18T08:59:29.802-0300    [31mERROR[0m  spin    spin/hosts.go:63        Failed to sync HOST contracts: payout status batch returned wrong length of contracts, need 1013, got 100
BTFS is up-to-date.

**Comment by taiyangc** [comment] 2020-08-18 14:21
Duplicate of #624 Please subscribe for updates there.

**Closed by taiyangc** 2020-08-18 14:21 UTC
