### ISSUE TITLE
Uptime goes up one day and down another day

### ISSUE THREAD

**Issue by raisro** [TRON-US/go-btfs#858] opened 2020-12-19 11:58 UTC
Hi, 

Uptime changes between 96% and 98% depending on the day. Is this something normal?

This node was born on 11/19/2020 (Host Score: 7.4/10) but on 12/04/2020 (Host Score: 8.4/10) the router was down for 24 hours or so. 

From 12/05/2020 (H.Score: 9.4/10) to today 12/18/2020 (H.Score: 9.4/10) the Host Score has not changed, how long does the host need for 100% uptime, it is currently 60%

Do I have to wait around 30 days?, Could there be a problem with this host?.

I want to see the host working, i'm impatient.
;)

[screenshots.pdf](https://github.com/TRON-US/go-btfs/files/5719355/screenshots.pdf)

BR,
Raúl.

**Comment by taiyangc** [comment] 2020-12-24 03:11
Please check #828, likely a duplicate of that issue.

**Closed by taiyangc** 2020-12-24 03:11 UTC
