### ISSUE TITLE
0 contracts and no payment date

### ISSUE THREAD

**Issue by WhiteHeadbanger** [TRON-US/go-btfs#660] opened 2020-08-21 19:43 UTC
#### Version information:
go-btfs version: 1.3.6-b1722d1
Repo version: 9
System version: amd64/windows
Golang version: go1.14.6

#### Description:
Peer ID: 	16Uiu2HAm6aHyva9NKfwJecfgVftnJ4t7WjLbR6ZTwNqdrHL5JqY7

Since my payment on August 8th, the contracts counter on the Host UI had lower to 0, although I still have a bunch of GB hosted in my HDD.
I'm still getting paid, that's no problem, I just don't know if this is intended, or if it's a bug. For reference, I have +1000 contracts. I know that because of the error details from the past version.  

Please if you need more info, don't hesitate in asking.

**Edit:** forgot to add a screenshot
![image](https://user-images.githubusercontent.com/12226415/90928671-b3a5a680-e3cd-11ea-8f1b-ed83bf6f3b16.png)

Thanks

**Comment by taiyangc** [comment] 2020-08-24 18:54
We've found some data issue but still trying to find the root cause.

Sorry we don't have doc ready for the json. We will add more descriptions in the future.

**Comment by WhiteHeadbanger** [comment] 2020-08-24 22:43
> We've found some data issue but still trying to find the root cause.
> 
> Sorry we don't have doc ready for the json. We will add more descriptions in the future.

No problem mate, you all are doing great :)
Let me know please if I shall do something else

**Comment by WhiteHeadbanger** [comment] 2020-09-04 21:23
Is there any news?

**Comment by taiyangc** [comment] 2020-09-22 07:36
Yes, this will be fully fixed in upcoming v1.4.0. Thanks for your patience.

**Comment by WhiteHeadbanger** [comment] 2020-09-22 23:31
Thank you!

**Comment by taiyangc** [comment] 2020-09-28 18:46
v1.4.0 is released and addressed this issue.

**Closed by taiyangc** 2020-09-28 18:46 UTC
