### ISSUE TITLE
Runtime Error: slice bounds out of range [:630]

### ISSUE THREAD

**Issue by Crypto72** [TRON-US/go-btfs#889] opened 2021-01-26 09:10 UTC
I am having this error everyday. After the btfs daemon is running for few hours without errors it goes into panic and stops.

T:\btfs>btfs daemon
Initializing daemon...
go-btfs version: 1.5.0-86e6633
Repo version: 10
System version: amd64/windows
Golang version: go1.15.6
Repo location: T:\btfs
Peer identity: 16Uiu2HAm37e4LJ5RCtcVDrESGMS1oLU1B73eTEV2qLLY23HxbtSh
Swarm listening on /ip4/127.0.0.1/tcp/1234
Swarm listening on /ip4/169.254.172.139/tcp/1234
Swarm listening on /ip4/192.168.0.17/tcp/1234
Swarm listening on /ip6/::1/tcp/1234
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/1234
Swarm announcing /ip4/192.168.0.17/tcp/1234
Swarm announcing /ip6/::1/tcp/1234
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
HostUI: http://127.0.0.1:5001/hostui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Remote API server listening on /ip4/127.0.0.1/tcp/5101
Daemon is ready
Storage host info will be synced at [SCORE] mode
Current host stats will be synced
Current host settings will be synced
BTFS is up-to-date.
panic: runtime error: slice bounds out of range [:630] with capacity 2

goroutine 6153276 [running]:
github.com/libp2p/go-libp2p-pnet.(*pskConn).Read(0xc011089580, 0xc007ea86c8, 0x2, 0x2, 0xc0126c9b30, 0x40c0ac, 0x1ba7ac0
)
        pkg/mod/github.com/libp2p/go-libp2p-pnet@v0.2.0/psk_conn.go:43 +0x24c
io.ReadAtLeast(0x2cd91d78, 0xc011089580, 0xc007ea86c8, 0x2, 0x2, 0x2, 0x481245, 0xc018b165a0, 0xc0126c9ba8)
        /usr/local/go/src/io/io.go:314 +0x8e
io.ReadFull(...)
        /usr/local/go/src/io/io.go:333
github.com/libp2p/go-libp2p-noise.(*secureSession).readNextInsecureMsgLen(0xc007ea8640, 0x0, 0xc0126c9be8, 0x46a09e)
        pkg/mod/github.com/libp2p/go-libp2p-noise@v0.1.1/rw.go:134 +0x93
github.com/libp2p/go-libp2p-noise.(*secureSession).Read(0xc007ea8640, 0xc011985000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        pkg/mod/github.com/libp2p/go-libp2p-noise@v0.1.1/rw.go:53 +0x205
bufio.(*Reader).fill(0xc005f323c0)
        /usr/local/go/src/bufio/bufio.go:101 +0x10a
bufio.(*Reader).ReadByte(0xc005f323c0, 0xc00b98d458, 0xcda0b9278e2c, 0x0)
        /usr/local/go/src/bufio/bufio.go:253 +0x45
encoding/binary.ReadUvarint(0x2d75d40, 0xc005f323c0, 0x46f952, 0xc00b98d458, 0x1)
        /usr/local/go/src/encoding/binary/varint.go:110 +0x8d
github.com/libp2p/go-mplex.(*Multiplex).readNextHeader(0xc005766100, 0xc0126c9d01, 0x4, 0x0, 0x0)
        pkg/mod/github.com/libp2p/go-mplex@v0.1.2/multiplex.go:548 +0x46
github.com/libp2p/go-mplex.(*Multiplex).handleIncoming(0xc005766100)
        pkg/mod/github.com/libp2p/go-mplex@v0.1.2/multiplex.go:367 +0xef
created by github.com/libp2p/go-mplex.NewMultiplex
        pkg/mod/github.com/libp2p/go-mplex@v0.1.2/multiplex.go:105 +0x212

I am looking forward to receive your feedback about this. 

Cheers,
Tony

**Comment by taiyangc** [comment] 2021-01-27 03:19
Duplicate of #736 Since it's an upstream bug we may need some help in debugging/fixing it.

**Closed by taiyangc** 2021-01-27 03:19 UTC
